name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x, 20.x]
    
    env:
      CI: true

    steps:
    - uses: actions/checkout@v3
    - name: Use Node ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Lint
      run: npm run lint
    - name: Run Kafka
      run: docker-compose up -d
    - name: Wait for dependencies
      run: node scripts/waitForKafka.js
    - name: Run tests
      run: npm test
    - name: Verify types
      run: npm run test:types